name: sos
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

#--------------------------- Packages ---------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.5.0
  intl: ^0.18.0
  logger: ^2.6.1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1  
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.0.5
  get: ^4.6.5
  get_storage: ^2.1.1

# -------------------------- ./ Packages  End -------------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------------------- Local Assets ---------------------------#
  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/illustrations/
    - assets/images/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/icons/
    

 
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
